import checkoutPetModel from './checkoutPetModel';
const {
  formField: {
    nome,
    especie,
    sexo,
    descricao,
    // descricao_comportamento,
    porte,
    idade,
    anos,
    meses,
    latitude,
    longitude,
    url_foto,
    // id_usuario,
    castrado,
    cidade,
    cor,
    cuidados_veterinarios,
    raca,
    uf,
    cep,
    vacinado,
    vermifungado,
    adocao,
    perdido,
  }
} = checkoutPetModel;

export default {
  [nome.name]: '',
  [especie.name]: '',
  [sexo.name]: '',
  [descricao.name] : '',
  [porte.name] : '',
  [idade.name] : '',
  [anos.name] : '',
  [meses.name] : '',
  [latitude.name] : '',
  [longitude.name] : '',
  [url_foto.name] : '',
  [castrado.name] : false,
  [cidade.name] : '',
  [cep.name] : '',
  [cor.name] : '',
  [cuidados_veterinarios.name] : false,
  [raca.name] : '',
  [uf.name] : '',
  [vacinado.name] : false,
  [vermifungado.name] : false,
  [adocao.name] : true,
  [perdido.name] : false,
};